import { RBAC_ACTIONS, RBAC_SUBJECTS } from '../../src/common/constants/global.constants';
import { Permission, PrismaClient } from '@prisma/client';

export const permissionSeedData: Permission[] = [
  {
    //admin permission
    id: 1,
    action: 'manage',
    subject: 'all',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    conditions: undefined,
    inverted: false,
    reason: null,
    permissionName: 'Admin Permission',
  },
  {
    //user create permission
    id: 2,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.USER,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    conditions: undefined,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create user data',
  },
  {
    //user read permission
    id: 3,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.USER,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to read user data',
  },
  {
    //user update permission
    id: 4,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.USER,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update user data',
  },
  {
    //user delete permission
    id: 5,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.USER,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to delete user data',
  },
  {
    //user manage access - all CRUD
    id: 6,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.USER,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to user',
  },
  {
    //ROLE create permission
    id: 7,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.ROLE,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    conditions: undefined,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create ROLE data',
  },
  {
    //ROLE read permission
    id: 8,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.ROLE,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to read ROLE data',
  },
  {
    //ROLE update permission
    id: 9,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.ROLE,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update ROLE data',
  },
  {
    //ROLE delete permission
    id: 10,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.ROLE,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to delete ROLE data',
  },
  {
    //ROLE manage access - all CRUD
    id: 11,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.ROLE,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to ROLE',
  },
  {
    //TRAIL create permission
    id: 12,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.TRAIL,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    conditions: undefined,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create TRAIL data',
  },
  {
    //TRAIL read permission
    id: 13,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.TRAIL,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to read TRAIL data',
  },
  {
    //TRAIL update permission
    id: 14,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.TRAIL,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update TRAIL data',
  },
  {
    //TRAIL delete permission
    id: 15,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.TRAIL,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to delete TRAIL data',
  },
  {
    //TRAIL manage access - all CRUD
    id: 16,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.TRAIL,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to TRAIL',
  },
  {
    //AUTH create permission
    id: 17,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.AUTH,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    conditions: undefined,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create AUTH data',
  },
  {
    //AUTH update permission
    id: 19,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.AUTH,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update AUTH data',
  },
  {
    //AUTH manage access - all CRUD
    id: 21,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.AUTH,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to AUTH',
  },
  {
    //FCM create permission
    id: 22,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.FCM,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    conditions: undefined,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create FCM data',
  },
  {
    //FCM read permission
    id: 23,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.FCM,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to read FCM data',
  },
  {
    //FCM delete permission
    id: 25,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.FCM,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to delete FCM data',
  },
  {
    //FCM manage access - all CRUD
    id: 26,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.FCM,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to FCM',
  },
  {
    //ONBOARDING_GIUDELINES update permission
    id: 29,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.ONBOARDING_GIUDELINES,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update ONBOARDING_GIUDELINES data',
  },
  {
    //ONBOARDING_GIUDELINES delete permission
    id: 30,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.ONBOARDING_GIUDELINES,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to delete ONBOARDING_GIUDELINES data',
  },
  {
    //ONBOARDING_GIUDELINES manage access - all CRUD
    id: 31,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.ONBOARDING_GIUDELINES,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to ONBOARDING_GIUDELINES',
  },
  {
    //POLICIES_AND_CONDITIONS read permission
    id: 33,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.POLICIES_AND_CONDITIONS,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to read POLICIES_AND_CONDITIONS data',
  },
  {
    //POLICIES_AND_CONDITIONS update permission
    id: 34,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.POLICIES_AND_CONDITIONS,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update POLICIES_AND_CONDITIONS data',
  },
  {
    //POLICIES_AND_CONDITIONS manage access - all CRUD
    id: 36,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.POLICIES_AND_CONDITIONS,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to POLICIES_AND_CONDITIONS',
  },
  {
    //Deny all permission on all resources
    id: 37,
    action: 'manage',
    subject: 'all',
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: true,
    reason: null,
    permissionName: 'Full acces to POLICIES_AND_CONDITIONS',
  },
  {
    //STAGE_TAG create permission
    id: 38,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.STAGE_TAG,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create STAGE_TAG data',
  },
  {
    //STAGE_TAG update permission
    id: 39,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.STAGE_TAG,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update STAGE_TAG data',
  },
  {
    //STAGE_TAG delete permission
    id: 41,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.STAGE_TAG,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to delete STAGE_TAG data',
  },
  {
    //POINT_OF_INTEREST create permission
    id: 42,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.POINT_OF_INTEREST,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    conditions: undefined,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create POINT_OF_INTEREST data',
  },
  {
    //POINT_OF_INTEREST read permission
    id: 43,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.POINT_OF_INTEREST,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to read POINT_OF_INTEREST data',
  },
  {
    //POINT_OF_INTEREST update permission
    id: 44,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.POINT_OF_INTEREST,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update POINT_OF_INTEREST data',
  },
  {
    //POINT_OF_INTEREST delete permission
    id: 45,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.POINT_OF_INTEREST,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to delete POINT_OF_INTEREST data',
  },
  {
    //POINT_OF_INTEREST manage access - all CRUD
    id: 46,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.POINT_OF_INTEREST,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to POINT_OF_INTEREST',
  },
  {
    //BADGES create permission
    id: 47,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.BADGES,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    conditions: undefined,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create BADGES data',
  },
  {
    //BADGES read permission
    id: 48,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.BADGES,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to read BADGES data',
  },
  {
    //BADGES update permission
    id: 49,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.BADGES,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update BADGES data',
  },
  {
    //BADGES delete permission
    id: 50,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.BADGES,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to delete BADGES data',
  },
  {
    //BADGES manage access - all CRUD
    id: 51,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.BADGES,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to BADGES',
  },
  {
    //PASS_INVENTORY create permission
    id: 52,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.PASS_INVENTORY,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    conditions: undefined,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create PASS_INVENTORY data',
  },
  {
    //PASS_INVENTORY read permission
    id: 53,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.PASS_INVENTORY,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to read PASS_INVENTORY data',
  },
  {
    //PASS_INVENTORY update permission
    id: 54,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.PASS_INVENTORY,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update PASS_INVENTORY data',
  },
  {
    //PASS_INVENTORY manage access - all CRUD
    id: 56,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.PASS_INVENTORY,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to PASS_INVENTORY data',
  },
  {
    //PASS_CONDITION update permission
    id: 59,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.PASS_CONDITION,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update PASS_CONDITION data',
  },
  {
    //PASS_CONDITION delete permission
    id: 60,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.PASS_CONDITION,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to delete PASS_CONDITION data',
  },
  {
    //PASS_CONDITION manage access - all CRUD
    id: 61,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.PASS_CONDITION,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to PASS_CONDITION data',
  },
  {
    //NOTIFICATIONS create permission
    id: 62,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.NOTIFICATIONS,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    conditions: undefined,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create NOTIFICATIONS data',
  },
  {
    //NOTIFICATIONS manage access - all CRUD
    id: 66,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.NOTIFICATIONS,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to NOTIFICATIONS data',
  },
  {
    //PROMOTIONS manage access - all CRUD
    id: 71,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.PROMOTIONS,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to PROMOTIONS data',
  },
  {
    //PASS create permission
    id: 72,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.PASS,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    conditions: undefined,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create PASS data',
  },
  {
    //PASS read permission
    id: 73,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.PASS,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to read PASS data',
  },
  {
    //PASS delete permission
    id: 75,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.PASS,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to delete PASS data',
  },
  {
    //PASS manage access - all CRUD
    id: 76,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.PASS,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full acces to PASS data',
  },
  {
    id: 77,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.REPORTED_IMAGES,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full access to REPORTED_IMAGES data',
  },
  {
    id: 82,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.TRAIL_TRACKING,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full access to TRAIL_TRACKING data',
  },
  {
    id: 86,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.TRAIL_TRACKING,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'READ access to TRAIL_TRACKING data',
  },
  {
    id: 87,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.STAGE_WISE_SUMMARY,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full access to STAGE_WISE_SUMMARY data',
  },
  {
    id: 92,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.AWARD_BADGE,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'CREATE access to AWARD_BADGE data',
  },
  {
    id: 93,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.CANCELLED_PASSES_REPORT,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full access to CANCELLED_PASSES_REPORT data',
  },
  {
    id: 94,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.ADMIN_PORTAL,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'MANAGE access to ADMIN_PORTAL',
  },
  {
    id: 95,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.DASHBOARD_PASSES,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'READ access to DASHBOARD PASSES data',
  },
  {
    id: 96,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.DASHBOARD_PASSES_CHART,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'READ access to DASHBOARD PASSES CHART data',
  },
  {
    id: 97,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.DASHBOARD_CONTENT_UPLOADED,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'READ access to DASHBOARD CONTENT UPLOADED data',
  },
  {
    id: 98,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.DASHBOARD_REPORTED_CONTENT,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'READ access to DASHBOARD REPORTED CONTENT data',
  },
  {
    id: 99,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.DASHBOARD_STAGES_CLOSED,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'READ access to DASHBOARD STAGES CLOSED data',
  },
  {
    //PERMISSION create permission
    id: 100,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.PERMISSION,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    conditions: undefined,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create PERMISSION data',
  },
  {
    //PERMISSION read permission
    id: 101,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.PERMISSION,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to read PERMISSION data',
  },
  {
    //PERMISSION update permission
    id: 102,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.PERMISSION,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update PERMISSION data',
  },
  {
    //PERMISSION delete permission
    id: 103,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.PERMISSION,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to delete PERMISSION data',
  },
  {
    //Stage translation update permission
    id: 104,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.STAGE_TRANSLATION,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update STAGE TRANSLATION data',
  },
  {
    //Story update permission
    id: 105,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.STORY,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to update STORY data',
  },
  {
    //Story create permission
    id: 106,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.STORY,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to create STORY data',
  },
  {
    //Story delete permission
    id: 107,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.STORY,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to delete STORY data',
  },
  {
    //Story read permission
    id: 108,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.STORY,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Give access to read STORY data',
  },
  // Noticeboard manage access - all CRUD
  {
    id: 109,
    action: RBAC_ACTIONS.MANAGE,
    subject: RBAC_SUBJECTS.NOTICEBOARD,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Full access to NOTICEBOARD data',
  },
  // Noticeboard create permission
  {
    id: 110,
    action: RBAC_ACTIONS.CREATE,
    subject: RBAC_SUBJECTS.NOTICEBOARD,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Create access to NOTICEBOARD data',
  },
  // Noticeboard read permission
  {
    id: 111,
    action: RBAC_ACTIONS.READ,
    subject: RBAC_SUBJECTS.NOTICEBOARD,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Read access to NOTICEBOARD data',
  },
  // Noticeboard delete permission
  {
    id: 112,
    action: RBAC_ACTIONS.DELETE,
    subject: RBAC_SUBJECTS.NOTICEBOARD,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Delete access to NOTICEBOARD data',
  },
  // Noticeboard update permission
  {
    id: 113,
    action: RBAC_ACTIONS.UPDATE,
    subject: RBAC_SUBJECTS.NOTICEBOARD,
    conditions: undefined,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    inverted: false,
    reason: null,
    permissionName: 'Update access to NOTICEBOARD data',
  },
];

const permissionSeedDelete: Permission[] = [];

const prisma = new PrismaClient();

export const seedPermissions = async (): Promise<void> => {
  await prisma.$transaction([
    ...permissionSeedData.map((permission) =>
      prisma.permission.upsert({
        where: { id: permission.id },
        update: permission,
        create: permission,
      }),
    ),
    prisma.permission.deleteMany({
      where: {
        id: {
          in: permissionSeedDelete.map((permissionRecord) => permissionRecord.id),
        },
      },
    }),
  ]);
};
