-- CreateEnum
CREATE TYPE "STAGE_MEDIA_KEY_TYPES" AS ENUM ('MAIN_IMAGE', 'SUPPLIMENTARY_IMAGE', 'ELEVATION_GRAPH_IMAGE');

-- AlterTable
ALTER TABLE "stage_media" ADD COLUMN     "media_type" "STAGE_MEDIA_KEY_TYPES" NOT NULL DEFAULT 'SUPPLIMENTARY_IMAGE';
