-- CreateEnum
CREATE TYPE "PEOPLE_INTERACTIONS" AS ENUM ('LOW', 'HIGH');

-- CreateEnum
CREATE TYPE "FAMILY_FRIENDLY_STATUS" AS ENUM ('YES', 'NO');

-- AlterTable
ALTER TABLE "stages" ADD COLUMN     "family_friendly_status" "FAMILY_FRIENDLY_STATUS" NOT NULL DEFAULT 'YES',
ADD COLUMN     "people_interaction" "PEOPLE_INTERACTIONS" NOT NULL DEFAULT 'LOW';
